- name: ansible command vs ansible shell
  hosts: local
  connection: local
  tasks:
  - name: shell module
    ansible.builtin.shell: cat /etc/passwd | grep root
    register: users_output

  - name: print output
    ansible.builtin.debug:
      msg: "{{users_output}}"

  - name: command module
    ansible.builtin.command: touch jai.txt
