- name: string to list conversion
  hosts: local
  connection: local
  vars:
    topics: linux, shell, ansible, terraform
  tasks:
    name: splitting based on cama
    ansible.builtin.debug:
      msg: "{{topics | split(',')}}"
