- name: check idempotancy
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: user creation
    ansible.builtin.user:
      name: jai # creating user jai, if jai exists it simply dont do anything
